name: Pets
main: me.giinger.pets.Pets
version: 1.0
author: Giinger
description: Have personal pets in minecraft
depend: [ParticleAPI, ControllableMobsAPI]
commands:
  petegg:
    description: Gives you a pet